### ISSUE TITLE
Spotify Auth crashes Rainmeter

### ISSUE THREAD

**Issue by KomaGR** [redsaph/cleartext#2]
At Rainmeter startup a Spotify Auth page pops requesting auth for SpotifyPlugin. I don't have Spotify connected. 
If I login with Spotify all goes well. But then again after reboot it still asks for auth.
If I don't login Rainmeter eventually crashes.
![spotifyauth](https://user-images.githubusercontent.com/22573447/37715345-6f0240a4-2d24-11e8-88a6-ef950c19e97f.png)

**Comment by tjhrulz** [comment]
Try installing the latest Spotify plugin and see if that helps https://github.com/RobertFrydenlund/SpotifyPlugin/releases

**Comment by tjhrulz** [comment]
Hey @redsaph btw you may want to do a hotfix for the time being for Cleartext so that it uses the SpotifyPlugin for the commands instead of NowPlaying until either Spotify patches it or they get back to me that they will not fix it so I can work on patch Rainmeter. It will only work though for premium users (I wish .raptor made it more obvious that it only worked with premium) but at least then that gives them something so you get less complaints about that.

If you need help figuring that out feel free to let me know and I can send a PR your way.
