### ISSUE TITLE
Issue: Latest update causes Rainmeter to hang and freeze

### ISSUE THREAD

**Issue by charmarkk** [redsaph/cleartext#4]
Pretty much self explanatory! I installed it the other day after info was inevitably not showing up since spotify updated their plugin - now ClearText is causing rainmeter to freeze. Can't even right click it in the sys tray or anything like that.

**Comment by redsaph** [comment]
Hi, the Spotify plugin has been discontinued by the original author because of Spotify's ever changing APIs. 

You can update to the latest version of Cleartext and use the default NowPlaying measure for Spotify _or_ do a mix of [WebNowPlaying](https://github.com/tjhrulz/WebNowPlaying) as the media player and [Spicetify](https://github.com/khanhas/Spicetify) to fetch data from the Spotify application.
